using System;

namespace Even_Fibonacci_numbers
{
	/// <summary>
	/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	/// </summary>
	class MainClass
	{
		public static void Main (string[] args)
		{
			int max = 4000000;
			int currentNumber = 1;
			int previousNumber = 0;
			int sequence = 0;
			int sum = 0;

			while (sequence < max) {
				sequence = currentNumber + previousNumber;
				previousNumber = currentNumber;
				currentNumber = sequence;

				if (sequence % 2 == 0) {
					sum += sequence;
				}

				Console.WriteLine ("Sequence: " + sequence);
			}

			Console.WriteLine ("Sum: " + sum);
		}
	}
}
